@extends('layouts.app')

@section('content')
<div class="space-y-6">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 class="text-2xl font-bold text-gray-900">{{ $perumahan->nama_perumahan }}</h1><p class="mt-1 text-sm text-gray-500">Detail kawasan dan unit rumah.</p></div><div class="flex gap-2"><a href="{{ route('admin.perumahan.edit', $perumahan) }}" class="rounded-lg border border-gray-300 px-4 py-2.5 text-sm font-semibold text-gray-700 transition hover:bg-gray-50">Edit Perumahan</a><a href="{{ route('admin.unit-rumah.create', ['id_perumahan' => $perumahan->id]) }}" class="rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-primary-dark">Tambah Unit</a></div></div>

    <div class="grid gap-6 lg:grid-cols-3"><x-card class="lg:col-span-2"><div class="space-y-5">@if($perumahan->foto_kawasan)<img src="{{ asset('storage/' . $perumahan->foto_kawasan) }}" alt="{{ $perumahan->nama_perumahan }}" class="h-72 w-full rounded-xl object-cover">@else<div class="flex h-72 items-center justify-center rounded-xl bg-gray-100 text-gray-400">Foto kawasan belum tersedia</div>@endif<div><div class="mb-3 flex items-center justify-between"><h2 class="text-lg font-semibold text-gray-900">Informasi Perumahan</h2><x-badge :status="$perumahan->status" /></div><dl class="grid gap-4 text-sm sm:grid-cols-2"><div><dt class="text-gray-500">Kota/Kabupaten</dt><dd class="mt-1 font-medium text-gray-900">{{ $perumahan->kota }}</dd></div><div><dt class="text-gray-500">Provinsi</dt><dd class="mt-1 font-medium text-gray-900">{{ $perumahan->provinsi }}</dd></div><div><dt class="text-gray-500">Kode Pos</dt><dd class="mt-1 font-medium text-gray-900">{{ $perumahan->kode_pos ?: '-' }}</dd></div><div><dt class="text-gray-500">Koordinat</dt><dd class="mt-1 font-medium text-gray-900">{{ $perumahan->latitude && $perumahan->longitude ? $perumahan->latitude . ', ' . $perumahan->longitude : '-' }}</dd></div><div class="sm:col-span-2"><dt class="text-gray-500">Alamat</dt><dd class="mt-1 whitespace-pre-line font-medium text-gray-900">{{ $perumahan->alamat }}</dd></div>@if($perumahan->deskripsi)<div class="sm:col-span-2"><dt class="text-gray-500">Deskripsi</dt><dd class="mt-1 whitespace-pre-line text-gray-700">{{ $perumahan->deskripsi }}</dd></div>@endif</dl></div></div></x-card>
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-1"><x-card><p class="text-sm text-gray-500">Unit Tersedia</p><p class="mt-1 text-2xl font-bold text-gray-900">{{ $unitSummary['tersedia'] }}</p></x-card><x-card><p class="text-sm text-gray-500">Unit Di-booking</p><p class="mt-1 text-2xl font-bold text-gray-900">{{ $unitSummary['dibooking'] }}</p></x-card><x-card><p class="text-sm text-gray-500">Unit Terjual</p><p class="mt-1 text-2xl font-bold text-gray-900">{{ $unitSummary['dijual'] }}</p></x-card><x-card><p class="text-sm text-gray-500">Unit Dibatalkan</p><p class="mt-1 text-2xl font-bold text-gray-900">{{ $unitSummary['dibatalkan'] }}</p></x-card></div>
    </div>

    <x-card title="Unit Rumah" :subtitle="$perumahan->unit_rumah_count . ' unit terdaftar di perumahan ini.'"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200 text-sm"><thead class="bg-gray-50 text-left text-xs font-semibold uppercase tracking-wide text-gray-500"><tr><th class="px-4 py-3">Kode Unit</th><th class="px-4 py-3">Tipe</th><th class="px-4 py-3">Kategori</th><th class="px-4 py-3">Harga Jual</th><th class="px-4 py-3">Status</th></tr></thead><tbody class="divide-y divide-gray-100 bg-white">@forelse($units as $unit)<tr><td class="px-4 py-4 font-semibold text-gray-900">{{ $unit->kode_unit }}</td><td class="px-4 py-4 text-gray-700">{{ $unit->tipe_rumah }}</td><td class="px-4 py-4"><x-badge :status="$unit->kategori->value" /></td><td class="px-4 py-4 text-gray-700">Rp {{ number_format((float) $unit->harga_jual, 0, ',', '.') }}</td><td class="px-4 py-4"><x-badge :status="$unit->status_unit->value" /></td></tr>@empty<tr><td colspan="5" class="px-4 py-12 text-center text-gray-500">Belum ada unit rumah di perumahan ini.</td></tr>@endforelse</tbody></table></div><x-slot:footer><x-pagination :paginator="$units" /></x-slot:footer></x-card>
</div>
@endsection