@extends('layouts.app')

@section('content')
<div class="space-y-6">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 class="text-2xl font-bold text-gray-900">Data Unit Rumah</h1><p class="mt-1 text-sm text-gray-500">Kelola unit rumah dan ketersediaannya.</p></div><a href="{{ route('admin.unit-rumah.create') }}" class="inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-primary-dark">+ Tambah Unit</a></div>
    <div class="grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><x-card><p class="text-sm text-gray-500">Unit Tersedia</p><p class="mt-1 text-2xl font-bold">{{ $summary['tersedia'] }}</p></x-card><x-card><p class="text-sm text-gray-500">Unit Di-booking</p><p class="mt-1 text-2xl font-bold">{{ $summary['dibooking'] }}</p></x-card><x-card><p class="text-sm text-gray-500">Unit Terjual</p><p class="mt-1 text-2xl font-bold">{{ $summary['dijual'] }}</p></x-card><x-card><p class="text-sm text-gray-500">Unit Batal</p><p class="mt-1 text-2xl font-bold">{{ $summary['dibatalkan'] }}</p></x-card></div>
    <x-card><form method="GET" class="grid gap-4 md:grid-cols-3 lg:grid-cols-5 lg:items-end"><x-form-input name="search" label="Cari Unit" placeholder="Kode unit atau tipe rumah" :value="request('search')" /><x-form-select name="id_perumahan" label="Perumahan" :options="$perumahan->all()" :selected="request('id_perumahan')" /><x-form-select name="kategori" label="Kategori" :options="['subsidi' => 'Subsidi', 'non_subsidi' => 'Non-Subsidi']" :selected="request('kategori')" /><x-form-select name="status_unit" label="Status" :options="['tersedia' => 'Tersedia', 'dibooking' => 'Di-booking', 'dijual' => 'Dijual', 'dibatalkan' => 'Dibatalkan']" :selected="request('status_unit')" /><x-form-select name="jenis_ketersediaan" label="Ketersediaan" :options="['ready_stock' => 'Ready Stock', 'indent' => 'Indent']" :selected="request('jenis_ketersediaan')" /><div class="mb-4 flex gap-2"><button class="rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-white hover:bg-primary-dark">Terapkan</button>@if(request()->hasAny(['search','id_perumahan','kategori','status_unit','jenis_ketersediaan']))<a href="{{ route('admin.unit-rumah.index') }}" class="rounded-lg border border-gray-300 px-4 py-2.5 text-sm font-semibold text-gray-700">Reset</a>@endif</div></form></x-card>
    <x-card><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200 text-sm"><thead class="bg-gray-50 text-left text-xs font-semibold uppercase tracking-wide text-gray-500"><tr><th class="px-4 py-3">No</th><th class="px-4 py-3">Foto</th><th class="px-4 py-3">Kode Unit</th><th class="px-4 py-3">Perumahan</th><th class="px-4 py-3">Tipe</th><th class="px-4 py-3">Kategori</th><th class="px-4 py-3">Luas T/B</th><th class="px-4 py-3">Harga</th><th class="px-4 py-3">Status</th><th class="px-4 py-3 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-gray-100 bg-white">@forelse($units as $unit)<tr class="hover:bg-gray-50"><td class="px-4 py-4">{{ $units->firstItem() + $loop->index }}</td><td class="px-4 py-4">@if($unit->foto_unit)<img src="{{ asset('storage/' . $unit->foto_unit) }}" alt="{{ $unit->kode_unit }}" class="h-12 w-16 rounded-lg object-cover">@else<span class="flex h-12 w-16 items-center justify-center rounded-lg bg-gray-100 text-xs text-gray-400">Tidak ada</span>@endif</td><td class="px-4 py-4 font-semibold">{{ $unit->kode_unit }}</td><td class="px-4 py-4">{{ $unit->perumahan->nama_perumahan }}</td><td class="px-4 py-4">{{ $unit->tipe_rumah }}</td><td class="px-4 py-4"><x-badge :status="$unit->kategori->value" /></td><td class="px-4 py-4">{{ $unit->luas_tanah }}/{{ $unit->luas_bangunan }} m²</td><td class="px-4 py-4">Rp {{ number_format((float) $unit->harga_jual, 0, ',', '.') }}</td><td class="px-4 py-4"><x-badge :status="$unit->status_unit->value" /></td><td class="px-4 py-4 text-right"><div class="inline-flex items-center gap-3"><a href="{{ route('admin.unit-rumah.show', $unit) }}" class="font-semibold text-info">Detail</a><a href="{{ route('admin.unit-rumah.edit', $unit) }}" class="font-semibold text-primary">Edit</a><x-confirm-delete :route="route('admin.unit-rumah.destroy', $unit)" :item-name="$unit->kode_unit" /></div></td></tr>@empty<tr><td colspan="10" class="px-4 py-12 text-center text-gray-500">Data unit rumah tidak ditemukan.</td></tr>@endforelse</tbody></table></div><x-slot:footer><x-pagination :paginator="$units" /></x-slot:footer></x-card>
</div>
@endsection
